deployment:
  tasks:
    - export NODE_ENV=production
    - source /home/pcqhofjh/nodevenv/moh.xdrip.io/18/bin/activate
    - /bin/echo "Starting deployment"
    - /bin/echo "Pulling the latest changes from GitHub..."
    - /usr/bin/git pull
    - /bin/echo "Clearing node_modules..."
    - /bin/rm -rf node_modules
    - /bin/echo "Installing dependencies..."
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /bin/echo "Clearing .next..."
    - /bin/rm -rf .next
    - /bin/echo "Building the project..."
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /bin/echo "Restarting the application..."
    - /usr/local/cpanel/scripts/restartsrv_apache_php_fpm
    - /bin/echo "Deployment complete"
