deployment:
  tasks:
    - export NODE_ENV=production
    - source /home/pcqhofjh/nodevenv/moh.xdrip.io/18/bin/activate
    - /bin/echo "Starting deployment"
    - /bin/echo "Pulling the latest changes from GitHub..."
    - /usr/bin/git pull
    - /bin/echo "Checking and installing dependencies if necessary..."
    # Only install dependencies if node_modules is missing or outdated
    - if [ ! -d "node_modules" ]; then /opt/cpanel/ea-nodejs18/bin/npm install; fi
    - /bin/echo "Building the project..."
    # Ensure .next isn't cleared automatically every deploy
    - if [ ! -d ".next" ]; then /opt/cpanel/ea-nodejs18/bin/npm run build; fi
    - /bin/echo "Restarting the application..."
    - /usr/local/cpanel/scripts/restartsrv_apache_php_fpm
    - /bin/echo "Deployment complete"
